Refine reboot2

diff --git a/fix-files/target/linux/x86/base-files/sbin/reboot2 b/fix-files/target/linux/x86/base-files/sbin/reboot2
--- a/fix-files/target/linux/x86/base-files/sbin/reboot2
+++ b/fix-files/target/linux/x86/base-files/sbin/reboot2
@@ -1,15 +1,13 @@
-if [ -f /boot/grub/grub.cfg ]; then
-	if [ ! -z $1 ]; then
-		EXP=$1
-	elif grep 'default="0"' /boot/grub/grub.cfg > /dev/null; then
-		EXP=1
-	else       
-		EXP=0
-	fi
-	sed -i "s/default=\".*\"/default=\"$EXP\"/" /boot/grub/grub.cfg
-else
-	echo "/boot/grub/grub.cfg not found"
-	exit
+#!/bin/sh
+[ ! -f /boot/grub/grub.cfg ] && (echo "/boot/grub/grub.cfg not found"; exit 1)
+
+if [ $1 ]; then
+	EXP=$1
+elif grep 'default="0"' /boot/grub/grub.cfg > /dev/null; then
+	EXP=1
+else       
+	EXP=0
 fi
+sed -i "s/default=\".*\"/default=\"$EXP\"/" /boot/grub/grub.cfg
 echo Boot to $EXP
 reboot
diff --git a/n1-files/sbin/reboot2 b/n1-files/sbin/reboot2
--- a/n1-files/sbin/reboot2
+++ b/n1-files/sbin/reboot2
@@ -1,13 +1,11 @@
-if [ -f /boot/uEnv.txt ]; then
-	if grep 'mmcblk2p3' /boot/uEnv.txt > /dev/null; then
-		EXP=2
-	else
-		EXP=3
-	fi
-	sed -i "s|root=.* rootfs|root=/dev/mmcblk2p${EXP} rootfs|" /boot/uEnv.txt
+#!/bin/sh
+[ ! -f /boot/uEnv.txt ] && (echo "/boot/uEnv.txt not found"; exit 1)
+
+if grep 'EMMC_ROOTFS2' /boot/uEnv.txt > /dev/null; then
+	ROOT=EMMC_ROOTFS1
 else
-	echo "/boot/uEnv.txt not found"
-	exit
+	ROOT=EMMC_ROOTFS2
 fi
-echo Boot to $EXP
+sed -i 's/root=.* rootfs/root=LABEL="$ROOT" rootfs/' /boot/uEnv.txt
+echo Boot to $ROOT
 reboot
